apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gemini-chat.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "gemini-chat.labels" . | nindent 4 }}
type: Opaque
stringData:
  GEMINI_API_KEY: {{ .Values.geminiApiKey | quote }}
